# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'T-Top' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for T-Top

   pod 'Spring', :git => 'https://github.com/MengTo/Spring.git'
   pod 'Arrow'

end
